//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerNameSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlannerNameSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Work Item.
        /// </summary>
        public static string CreateWorkItemHeader {
            get {
                return ResourceManager.GetString("CreateWorkItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to save item: .
        /// </summary>
        public static string DatastoreErrorSavingItem {
            get {
                return ResourceManager.GetString("DatastoreErrorSavingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving item....
        /// </summary>
        public static string DatastoreSavingItem {
            get {
                return ResourceManager.GetString("DatastoreSavingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the product: .
        /// </summary>
        public static string DatastoreUnableToConnectError {
            get {
                return ResourceManager.GetString("DatastoreUnableToConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Manager requires that Product Studio be installed on your machine in order to continue.  If you haven&apos;t done so already, please install the latest version of Product Studio, and then launch the application again..
        /// </summary>
        public static string DatastoreUnableToConnectNextSteps {
            get {
                return ResourceManager.GetString("DatastoreUnableToConnectNextSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sprint.
        /// </summary>
        public static string EditSprintHeader {
            get {
                return ResourceManager.GetString("EditSprintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or Move Task.
        /// </summary>
        public static string EditTaskHeader {
            get {
                return ResourceManager.GetString("EditTaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or Move Work Item.
        /// </summary>
        public static string EditWorkItemHeader {
            get {
                return ResourceManager.GetString("EditWorkItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message: .
        /// </summary>
        public static string ExceptionMessageLabel {
            get {
                return ResourceManager.GetString("ExceptionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GenericProfile {
            get {
                object obj = ResourceManager.GetObject("GenericProfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your team&apos;s backlog and work items....
        /// </summary>
        public static string LoadingHostItemDataMessage {
            get {
                return ResourceManager.GetString("LoadingHostItemDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading scheduling data....
        /// </summary>
        public static string LoadingScheduleDataMessage {
            get {
                return ResourceManager.GetString("LoadingScheduleDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening your sprint: .
        /// </summary>
        public static string OpeningSprintMessage {
            get {
                return ResourceManager.GetString("OpeningSprintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing your sprint: .
        /// </summary>
        public static string RefreshingSprintMessage {
            get {
                return ResourceManager.GetString("RefreshingSprintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you specified is already in use by another sprint - please try a different name..
        /// </summary>
        public static string SpintNameInUse {
            get {
                return ResourceManager.GetString("SpintNameInUse", resourceCulture);
            }
        }
    }
}
